DROP TABLE NAMECARD;

CREATE TABLE NAMECARD(
    NO NUMBER CONSTRAINT PK_NAMECARD PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    MOBILE VARCHAR2(20) NOT NULL,
    EMAIL VARCHAR2(40),
    COMPANY VARCHAR2(60)
);

DROP SEQUENCE CARD_NO;

CREATE SEQUENCE CARD_NO
INCREMENT BY 1
START WITH 1;

INSERT INTO NAMECARD VALUES
(
    CARD_NO.NEXTVAL,
    'È«±æµ¿',
    '010-000-0000',
    'HONG@gmail.com',
    '±¸±Û'
);

SELECT * FROM NAMECARD;
DELETE FROM NAMECARD;

commit;
rollback;
DELETE FROM NAMECARD
WHERE NO BETWEEN 3 AND 30;

